import { useEffect, useState, type FormEvent } from "react";
import { ArrowLeft, Save } from "lucide-react";
import { Link, useNavigate, useParams } from "react-router-dom";

import { ErrorMessage, toastDanger, toastSuccess } from "@/components/ui";
import { adminClassesApi, type ClassFormPayload, type ClassStatus } from "@/features/admin/classes/api/admin-classes-api";
import { adminBillingPoliciesApi, type AdminBillingPolicy } from "@/features/admin/billing-policies/api/admin-billing-policies-api";
import { adminRoomsApi, type AdminRoom } from "@/features/admin/classes/api/admin-rooms-api";
import { adminCoursesApi, type AdminCourse } from "@/features/admin/courses/api/admin-courses-api";
import styles from "@/features/admin/students/pages/StudentCreatePage.module.scss";
import { adminTeachersApi, type AdminTeacher } from "@/features/admin/teachers/api/admin-teachers-api";
import { getAuthErrorMessage } from "@/features/public/auth/api/auth-api";

type Props = { mode: "create" | "edit" };
type FormState = { courseId: string; teacherId: string; roomId: string; billingPolicyId: string; code: string; name: string; startDate: string; endDate: string; capacity: string; tuitionFeeSnapshot: string; totalSessions: string; completedSessions: string; status: ClassStatus; openedAt: string; closedAt: string; notes: string };
type FormErrors = Partial<Record<keyof FormState, string>>;
const statuses: Array<{ value: ClassStatus; label: string }> = [{ value: "Draft", label: "Nháp" }, { value: "Open", label: "Mở đăng ký" }, { value: "Ongoing", label: "Đang học" }, { value: "Completed", label: "Hoàn thành" }, { value: "Cancelled", label: "Đã hủy" }];
const numericStatus: Record<string, ClassStatus> = { "1": "Draft", "2": "Open", "3": "Ongoing", "4": "Completed", "5": "Cancelled" };
const initialForm: FormState = { courseId: "", teacherId: "", roomId: "", billingPolicyId: "", code: "", name: "", startDate: "", endDate: "", capacity: "1", tuitionFeeSnapshot: "", totalSessions: "", completedSessions: "0", status: "Draft", openedAt: "", closedAt: "", notes: "" };
const formatMoney = (value: string | number) => value === "" ? "" : new Intl.NumberFormat("en-US").format(Number(String(value).replace(/,/g, "")) || 0);
const toNumber = (value: string) => Number(value.replace(/,/g, ""));
const toLocalDateTime = (value?: string | null) => value ? value.slice(0, 16) : "";

export function ClassFormPage({ mode }: Props) {
  const navigate = useNavigate(); const { recordId } = useParams(); const isEditMode = mode === "edit";
  const [courses, setCourses] = useState<AdminCourse[]>([]); const [teachers, setTeachers] = useState<AdminTeacher[]>([]); const [rooms, setRooms] = useState<AdminRoom[]>([]); const [billingPolicies, setBillingPolicies] = useState<AdminBillingPolicy[]>([]);
  const [form, setForm] = useState(initialForm); const [errors, setErrors] = useState<FormErrors>({}); const [isLoading, setIsLoading] = useState(isEditMode); const [isSubmitting, setIsSubmitting] = useState(false);

  useEffect(() => { Promise.all([adminCoursesApi.getList({ page: 1, pageSize: 1000, sortBy: "name", isDescending: false }), adminTeachersApi.getList({ page: 1, pageSize: 1000, sortBy: "fullName", isDescending: false }), adminRoomsApi.getList(), adminBillingPoliciesApi.getList({ page: 1, pageSize: 20, isActive: true, isDescending: false })])
    .then(([courseResult, teacherResult, roomResult, policyResult]) => { setCourses(courseResult.items); setTeachers(teacherResult.items); setRooms(roomResult); setBillingPolicies(policyResult.items); }).catch((error) => toastDanger(getAuthErrorMessage(error))); }, []);
  useEffect(() => { if (!isEditMode || !recordId) return; let mounted = true; adminClassesApi.getById(recordId).then((record) => { if (!mounted) return; setForm({ courseId: String(record.courseId), teacherId: String(record.teacherId), roomId: record.roomId ? String(record.roomId) : "", billingPolicyId: record.billingPolicyId ? String(record.billingPolicyId) : "", code: record.code, name: record.name, startDate: record.startDate, endDate: record.endDate, capacity: String(record.capacity), tuitionFeeSnapshot: formatMoney(record.tuitionFeeSnapshot), totalSessions: String(record.totalSessions), completedSessions: String(record.completedSessions), status: typeof record.status === "number" ? numericStatus[String(record.status)] : record.status, openedAt: toLocalDateTime(record.openedAt), closedAt: toLocalDateTime(record.closedAt), notes: record.notes ?? "" }); }).catch((error) => toastDanger(getAuthErrorMessage(error))).finally(() => { if (mounted) setIsLoading(false); }); return () => { mounted = false; }; }, [isEditMode, recordId]);
  const update = <Key extends keyof FormState>(key: Key, value: FormState[Key]) => { setForm((current) => ({ ...current, [key]: value })); setErrors((current) => ({ ...current, [key]: undefined })); };
  const validate = () => { const next: FormErrors = {}; if (!form.courseId) next.courseId = "Vui lòng chọn khóa học."; if (!form.teacherId) next.teacherId = "Vui lòng chọn nhân viên."; if (!form.code.trim()) next.code = "Vui lòng nhập mã lớp."; else if (form.code.trim().length > 50) next.code = "Mã lớp không được vượt quá 50 ký tự."; if (!form.name.trim()) next.name = "Vui lòng nhập tên lớp."; else if (form.name.trim().length > 255) next.name = "Tên lớp không được vượt quá 255 ký tự."; if (!form.startDate) next.startDate = "Vui lòng chọn ngày bắt đầu."; if (!form.endDate) next.endDate = "Vui lòng chọn ngày kết thúc."; else if (form.startDate && form.endDate < form.startDate) next.endDate = "Ngày kết thúc không được trước ngày bắt đầu."; if (Number(form.capacity) <= 0) next.capacity = "Sĩ số phải lớn hơn 0."; if (form.totalSessions && Number(form.totalSessions) < 0) next.totalSessions = "Tổng số buổi không được nhỏ hơn 0."; if (Number(form.completedSessions) < 0) next.completedSessions = "Số buổi đã hoàn thành không được nhỏ hơn 0."; if (form.notes.length > 2000) next.notes = "Ghi chú không được vượt quá 2000 ký tự."; setErrors(next); return Object.keys(next).length === 0; };
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!validate() || isSubmitting) return; const payload: ClassFormPayload = { courseId: Number(form.courseId), teacherId: Number(form.teacherId), roomId: form.roomId ? Number(form.roomId) : null, billingPolicyId: form.billingPolicyId ? Number(form.billingPolicyId) : null, code: form.code.trim(), name: form.name.trim(), startDate: form.startDate, endDate: form.endDate, capacity: Number(form.capacity), tuitionFeeSnapshot: form.tuitionFeeSnapshot ? toNumber(form.tuitionFeeSnapshot) : null, totalSessions: form.totalSessions ? Number(form.totalSessions) : null, completedSessions: Number(form.completedSessions), status: form.status, openedAt: form.openedAt ? new Date(form.openedAt).toISOString() : null, closedAt: form.closedAt ? new Date(form.closedAt).toISOString() : null, notes: form.notes.trim() || null }; setIsSubmitting(true); try { if (isEditMode && recordId) { await adminClassesApi.update(recordId, { ...payload, id: Number(recordId) }); toastSuccess("Cập nhật lớp học thành công."); } else { await adminClassesApi.create(payload); toastSuccess("Tạo lớp học thành công."); } navigate("/admin/classes"); } catch (error) { toastDanger(getAuthErrorMessage(error)); } finally { setIsSubmitting(false); } };
  const input = (key: keyof FormState, label: string, type = "text") => <label className={styles.field}><span>{label} <em className={styles.requiredMark}>*</em></span><input type={type} value={form[key] as string} onChange={(event) => update(key, event.target.value as never)} /><ErrorMessage message={errors[key]} /></label>;
  return <div className={styles.page}><section className={styles.header}><div><Link className={styles.backLink} to="/admin/classes"><ArrowLeft size={16} /> Quay lại danh sách</Link><h1>{isEditMode ? "Chỉnh sửa lớp học" : "Tạo lớp học"}</h1></div></section><form className={styles.panel} onSubmit={submit}><div className={styles.panelHeader}><div><h2>Thông tin lớp học</h2><p>Cấu hình lớp học, nhân viên phụ trách, phòng và thời gian vận hành.</p></div></div>{isLoading ? <p className={styles.accountState}>Đang tải thông tin lớp học...</p> : <div className={styles.formGrid}>
    <label className={styles.field}><span>Khóa học <em className={styles.requiredMark}>*</em></span><select value={form.courseId} onChange={(event) => update("courseId", event.target.value)}><option value="">Chọn khóa học</option>{courses.map((course) => <option key={course.id} value={course.id}>{course.name}</option>)}</select><ErrorMessage message={errors.courseId} /></label>
    <label className={styles.field}><span>Nhân viên <em className={styles.requiredMark}>*</em></span><select value={form.teacherId} onChange={(event) => update("teacherId", event.target.value)}><option value="">Chọn nhân viên</option>{teachers.map((teacher) => <option key={teacher.id} value={teacher.id}>{teacher.fullName}</option>)}</select><ErrorMessage message={errors.teacherId} /></label>
    <label className={styles.field}><span>Phòng học</span><select value={form.roomId} onChange={(event) => update("roomId", event.target.value)}><option value="">Chưa chọn phòng</option>{rooms.map((room) => <option key={room.id} value={room.id}>{room.name} ({room.code})</option>)}</select></label>
    <label className={styles.field}><span>Chính sách học phí</span><select value={form.billingPolicyId} onChange={(event) => update("billingPolicyId", event.target.value)}><option value="">Để trống để sử dụng chính sách mặc định của khóa học</option>{billingPolicies.map((policy) => <option key={policy.id} value={policy.id}>{policy.name}</option>)}</select></label>
    {input("code", "Mã lớp")}{input("name", "Tên lớp")}{input("startDate", "Ngày bắt đầu", "date")}{input("endDate", "Ngày kết thúc", "date")}{input("capacity", "Sĩ số", "number")}
    <label className={styles.field}><span>Học phí lớp</span><input inputMode="numeric" placeholder="Để trống để lấy từ khóa học" value={form.tuitionFeeSnapshot} onChange={(event) => update("tuitionFeeSnapshot", formatMoney(event.target.value.replace(/[^\d]/g, "")))} /></label>
    <label className={styles.field}><span>Tổng số buổi</span><input min={0} placeholder="Để trống để lấy từ khóa học" type="number" value={form.totalSessions} onChange={(event) => update("totalSessions", event.target.value)} /><ErrorMessage message={errors.totalSessions} /></label>
    {input("completedSessions", "Số buổi đã hoàn thành", "number")}
    <label className={styles.field}><span>Trạng thái <em className={styles.requiredMark}>*</em></span><select value={form.status} onChange={(event) => update("status", event.target.value as ClassStatus)}>{statuses.map((status) => <option key={status.value} value={status.value}>{status.label}</option>)}</select></label>
    <label className={styles.field}><span>Ngày mở lớp</span><input type="datetime-local" value={form.openedAt} onChange={(event) => update("openedAt", event.target.value)} /></label><label className={styles.field}><span>Ngày đóng lớp</span><input type="datetime-local" value={form.closedAt} onChange={(event) => update("closedAt", event.target.value)} /></label>
    <label className={`${styles.field} ${styles.notesField}`}><span>Ghi chú</span><textarea rows={5} value={form.notes} onChange={(event) => update("notes", event.target.value)} /><ErrorMessage message={errors.notes} /></label>
  </div>}<div className={styles.formActions}><button className={styles.secondaryButton} type="button" onClick={() => navigate("/admin/classes")}>Hủy</button><button disabled={isLoading || isSubmitting} type="submit"><Save size={16} />{isSubmitting ? "Đang lưu..." : "Lưu lớp học"}</button></div></form></div>;
}
